import Nav from '@/components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Link from 'next/link'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Islam Media Organization',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Link rel='shorcut icon' href="favicon.png" type='image/x-icon' />
      </Head>
      <body className={inter.className}><Nav /> {children} <Footer /></body>
    </html>
  )
}
